### ISSUE TITLE
The 'bone' pool mentioned in Readme.md is undefined.

### ISSUE THREAD

**Issue by desert-rose** [brettwooldridge/HikariCP-benchmark#5]
When I ran the `./benchmark.sh -p pool=hikari,bone` command following the guide , NullPointException got thrown.

I checked the code of `BenchBase`, it seemed that 'bone' was undefined.

`@Param({ "hikari", "dbcp", "dbcp2", "tomcat", "c3p0", "vibur", "one" })
public String pool;`

        switch (pool)
        {
        case "hikari":
            setupHikari();
            break;
        case "tomcat":
            setupTomcat();
            break;
        case "dbcp":
            setupDbcp();
            break;
        case "dbcp2":
            setupDbcp2();
            break;
        case "c3p0":
            setupC3P0();
            break;
        case "vibur":
            setupVibur();
            break;
        case "one":
            setupOne();
            break;
        }

**Comment by brettwooldridge** [comment]
BoneCP was removed from the benchmark after they announced the project as deprecated.  You should be able to find a previous commit in the history where the BoneCP code is still present.
