### ISSUE TITLE
Do you compare with druid?

### ISSUE THREAD

**Issue by p0mp0k0** [brettwooldridge/HikariCP-benchmark#6]
Do you compare with druid,? It's a connection pool created by alibaba develop team, and it was called the best connection pool in chinese, so I want to know whose performance is better. 
The project at git is: https://github.com/alibaba/druid
Thanks.

**Comment by brettwooldridge** [comment]
Duplicate of [HikariCP#232](https://github.com/brettwooldridge/HikariCP/issues/232)
